# You are given an array of integers a. A new array b is generated by rearranging the 
# elements of a in the following way:

# b[0] is equal to a[0];
# b[1] is equal to the last element of a;
# b[2] is equal to a[1];
# b[3] is equal to the second-last element of a;
# b[4] is equal to a[2];
# b[5] is equal to the third-last element of a;
# and so on.
# Your task is to determine whether the new array b is sorted in strictly ascending order or not.

# Guaranteed constraints:
# 1 ≤ a.length ≤ 105,
# -109 ≤ a[i] ≤ 109.

def solution(a):
    prev = -10**10
    l, r = 0, len(a)-1
    
    while l < r:
        if a[l] <= prev or a[r] <= a[l]:
            return False
        prev = a[r]
        l += 1
        r -= 1
    if l == r:
        if a[l] <= prev:
            return False
            
    return True